### ISSUE TITLE
Support for ARM64 architectures

### ISSUE THREAD

**Issue by sjmach** [coroot/coroot#1]
Hello there,

I am trying coroot for an in-house kubernetes clusters deployed on Raspberry Pi 4 machines. I followed the installation guide but I am getting `exec /opt/coroot/coroot: exec format error` . This tells me that the arm64 arch is not supported. Considering all cloud providers like AWS, GCP, Oracle and now Azure have arm64 support, it would be great if we can get arm64 bit support.

**Comment by def** [comment]
Hi, @sjmach!

We definitely plan to add support for arm64. The task here is not just to compile Coroot for arm64, but to port and test the eBPF components of [coroot-node-agent](https://github.com/coroot/coroot-node-agent).

**Comment by apetruhin** [comment]
Latest versions of coroot and agents have arm64 support:
- ghcr.io/coroot/coroot:0.4.0
- ghcr.io/coroot/coroot-node-agent:1.1.0
- ghcr.io/coroot/coroot-pg-agent:1.2.0
- ghcr.io/coroot/coroot-aws-agent:1.1.0
