### ISSUE TITLE
No cost monitoring found in community edition

### ISSUE THREAD

**Issue by tuninger** [coroot/coroot#103]
I deployed the latest version via helm, but there is no cost monitoring tab, why is that?

Thanks in advance.

**Comment by apetruhin** [comment]
@tuninger, most likely, coroot-node-agent can not determine the `instance_type`  of your instances.
Could you please provide several samples of the `node_cloud_info` metric from your Prometheus?

**Comment by tuninger** [comment]
@apetruhin ，Thank you for your response. I am currently only deploying coroot in my local kubernetes cluster and do not see node_cloud_info related metrics in Prometheus metrics. 

Will this deployment result in no cost monitoring?

**Comment by apetruhin** [comment]
@tuninger, currently Cost Monitoring is available for AWS, GCP, and Azure instances.
