### ISSUE TITLE
Start failed! Help me!!!

### ISSUE THREAD

**Issue by lobsterHe** [coroot/coroot#104]
![3bbeca5bc827295196aeb24028f443e](https://github.com/coroot/coroot/assets/34124021/d1c311b2-6707-4893-a14e-c57e0dc83bef)
![8d3a9a5dc45e514518610e7b7c66748](https://github.com/coroot/coroot/assets/34124021/f03722be-e996-48b8-bae9-b6780f5d6a3b)
![e2a2725378d9a41d5402d1ddfeb11c4](https://github.com/coroot/coroot/assets/34124021/1602b2aa-e805-43d7-b57b-74c2ae803764)
why?why?why?

**Comment by apetruhin** [comment]
@lobsterHe,
Unfortunately, `coroot-node-agent` cannot run in docker-in-docker environments, such as minikube with the docker driver. However, on minikube with a VM-based driver (e.g., Hyperkit or VirtualBox), Coroot works fine.

[Here](https://github.com/coroot/coroot/issues/10#issuecomment-1345201225) is an explanation of the problem.

**Comment by lobsterHe** [comment]
Thank you, I'll try it now

**Comment by lobsterHe** [comment]
This is useful,thanks again.
![1699499336(1)](https://github.com/coroot/coroot/assets/34124021/2f58bc4e-6453-4eeb-8539-ac5a973255d5)
