### ISSUE TITLE
docker swarm services pattern

### ISSUE THREAD

**Issue by xhit** [coroot/coroot#108]
Currently we have some services in docker swarm with the same name, but not with the same stack in deploy, so the container_id pattern is:

```
/swarm/stack1/svc/1
/swarm/stack2/svc/1
```

In docker swarm it's not possible have two or more service name in same stack, so, the metrics should be collected with this rule applied and not with only the service name, because if we use the service name in other stack we cannot view information in coroot from both services.

In web app of coroot, to differentiate we can use `stack1/svc`

**Comment by def** [comment]
Could you please provide the link (URL) for one of these apps? The URL should include the namespace.

**Comment by xhit** [comment]
`http://stage01/p/2l2u4w8f/app/tts-api:DockerSwarmService:svc`

The stack changes when page refresh

**Comment by xhit** [comment]
Image 
![image](https://github.com/coroot/coroot/assets/51337247/abf375e2-302b-4395-9ed7-ee305c549714)

**Comment by xhit** [comment]
Yes

**Comment by def** [comment]
This issue is fixed in Coroot v0.22.0
@xhit, thank you for the report!

**Comment by xhit** [comment]
I tested and now shows the services! Thanks!

A little bug: In the SLO of the application, the client has the same namespace that is the application type of the app, in this case a external mongo db:

![image](https://github.com/coroot/coroot/assets/51337247/2d8a9e21-50da-4b58-be2d-2c284eebdef9)

**Comment by def** [comment]
I've fixed this bug too. It'll be part of the next Coroot release.
Thank you!
