### ISSUE TITLE
Pyroscope retention period config

### ISSUE THREAD

**Issue by rmn-lux** [coroot/coroot#109]
Hello, thank you for the coroot. I found out about this great product in an article on Habr.

I have a default installation in kubernetes via helm chart. Faced a problem that in pyroscope either retention doesn't work or I don't understand something. The space is clogged with metrics very quickly and is not cleared.   

The configuration was default, I reduced retention but eventually all the allocated space is clogged and everything stands at a standstill.

<img width="1244" alt="image" src="https://github.com/coroot/coroot/assets/6730162/c8869310-b933-4598-b6e4-bec2b36a7001">

On the screenshot above is an example: in the morning at 9.00 a clean install was done, and by the evening at 18.00 it was already 3 GB. Can you please tell me how to configure retention correctly so that it works and the metrics take up less space? Thanks.

P.S. I realize that the problem is not in coroot itself, but in a third-party product, but I hope you can tell me how to properly work with metrics in pyroscope or suggest some documentation on this issue.

UPD. for 21 hours of work accumulated logs of 8 GB already. there are no production services, test microservices are installed from https://github.com/GoogleCloudPlatform/microservices-demo.

**Comment by def** [comment]
@rmn-lux, starting from version 0.27, Coroot uses ClickHouse to store profiling data. The default TTL is set to 7 days, but you can [adjust](https://github.com/coroot/helm-charts/blob/main/charts/coroot/values.yaml#L114) it if necessary.
