### ISSUE TITLE
cpu throttling calculation 

### ISSUE THREAD

**Issue by uburro1** [coroot/coroot#11]
Hi guys!

I see in your documentation you counting throttling. 
![image](https://user-images.githubusercontent.com/88654436/208251454-4d94481c-55c8-48fc-9abc-b0fb10faff84.png)
I see coroot just has metric container_resources_cpu_throttled_seconds_total. Without period

`Coroot uses the [container_resources_cpu_throttled_seconds_total](https://coroot.com/docs/metric-exporters/node-agent/metrics#container_resources_cpu_throttled_seconds_total) metric to find out how long each container has been throttled for. If this metric of related containers is correlating with the application SLIs (Service Level Indicators), that means the lack of CPU time is caused by throttling.`

i search in your open code but did't find what kind of formula are  you use for calculation percent of throttling in container?

**Comment by def** [comment]
`rate(container_resources_cpu_throttled_seconds_total)` gives the number of seconds that the container was throttled per second, e.g. `500ms/second` means the container has been throttled 50% of this time

**Comment by uburro1** [comment]
thank you, Nikolay!

> `rate(container_resources_cpu_throttled_seconds_total[1m])` gives the number of seconds that the container was throttled per second, e.g. `500ms/second` means the container has been throttled 50% of this time
