### ISSUE TITLE
7th generation instances are not visible on the costs tab

### ISSUE THREAD

**Issue by gkalwig** [coroot/coroot#116]
Instances that belong to the AWS 7th generation, e.g. m7i, are not visible on the cost card.

![image](https://github.com/coroot/coroot/assets/87004230/d60348a6-86ed-44ce-8a78-fc1b9ddd0c02)
![image](https://github.com/coroot/coroot/assets/87004230/55f0aa8a-eb4d-4922-aab0-2a5fc0995f30)

**Comment by gkalwig** [comment]
If you think this could be connected to "spot". No, in another cluster where I have 6th and 7th gen, I only see 6th gen, no matter spot or on-demand:
![image](https://github.com/coroot/coroot/assets/87004230/58f19668-6381-43e3-98ec-1a715b1d70b9)

**Comment by def** [comment]
@gkalwig, thanks for the report. We've updated the cloud pricing data. 
Coroot automatically updates it once a day from GitHub, but you can force the update by restarting Coroot

**Comment by gkalwig** [comment]
Thanks, after restart looks good. 

You need to update that data manually? There is no pipeline to cyclic refresh it from AWS?

**Comment by def** [comment]
It's updated every day now
