### ISSUE TITLE
OCI OKE: Not getting service logs 

### ISSUE THREAD

**Issue by m-saied1990** [coroot/coroot#127]
coroot-node-agent:1.15.0
coroot:0.25.0
OKE: 1.26 

I'm not able to get services logs 
example: ![Screenshot 2023-12-10 at 11 15 25 PM](https://github.com/coroot/coroot/assets/98414136/cbaf8df4-e115-4a04-82d8-c4bcfc1e8eb0)

**Comment by def** [comment]
@m-saied1990, thank you for the report. This issue has been fixed in coroot-node-agent v1.15.1

**Comment by m-saied1990** [comment]
Thanks alot @def  , one more question is there any option to decrease the data retention of clickhouse data
