### ISSUE TITLE
ability to serve coroot at subpath

### ISSUE THREAD

**Issue by invisibl-dev** [coroot/coroot#13]
ability to serve coroot at subpath e.g example.com/coroot

**Comment by apetruhin** [comment]
@invisibl-dev,  https://github.com/coroot/coroot/releases/tag/0.12.1
The `--url-base-path` (`URL_BASE_PATH`) option can be used to set a subpath for Coroot.
For example,
```
 URL_BASE_PATH=/coroot/
```

**Comment by rjshrjndrn** [comment]
@apetruhin On a relative note, is there any suggested way to secure the UI? or shall I create a new issue for this?
Regards.
