### ISSUE TITLE
Cannot install coroot-node-agent

### ISSUE THREAD

**Issue by mkm29** [coroot/coroot#138]
I am attempting to replace/augment my obersavibility stack with coroot, on Kubernetes 1.28.4 on RKE2, replacing kube-proxy with Cilium 1.14.3.

I am using Flux to bootstrap my cluster(s) with the official kube-prometheus-stack, longhorn and ArgoCD. I am them using Argo to manage applications on my cluster, in this case starting with just coroot. I install both helm charts (coroot and node-agent), pointing coroot to the existing prometheus. However, when I access the coroot UI I get the following error: `No metrics found. Looks like you didn't install node-agent.`

I do not see where this (service) URL is configured but it installs the default `daemonset/coroot-node-agent`. It does not create a service for this though...

What is the recommended way to resolve this issue?

**Comment by def** [comment]
Make sure your Prometheus has discovered the agents. They should appear in Prometheus' target list. If you're using the Prometheus operator, you need to create a [PodMonitor](https://github.com/coroot/helm-charts/blob/main/charts/coroot/templates/podmonitor.yaml).

**Comment by mkm29** [comment]
Thanks it was creating a `PodMonitor` it just needed to have the `release: ...` label
