### ISSUE TITLE
Coroot reporting high cpu but prometheus is not

### ISSUE THREAD

**Issue by BertoSwanepoel** [coroot/coroot#142]
Hi,

We are getting alert and reports that some of our nodes are at 99% and 100% cpu usage. When adding a grafana to to the coroot prometheus and checking the node it reports 14% usage.
Any advise?
![Screenshot 2024-01-09 154128](https://github.com/coroot/coroot/assets/85493357/d094e236-0fb3-406b-a947-fe3b23f06615)
![Screenshot 2024-01-09 154159](https://github.com/coroot/coroot/assets/85493357/66431f9e-c240-41c0-8fa7-a7147f1a202f)

**Comment by def** [comment]
Coroot displays the current CPU usage (Grafana shows a 2-minute average). Please check the CPU usage chart on the affected node in Coroot.

**Comment by BertoSwanepoel** [comment]
This has been like this for more than a month, I have restarted the node agents a few times. I also updated the helm chart to the latest resulting in a restart/redeploy. here is the Chart for that node.
![image](https://github.com/coroot/coroot/assets/85493357/794f95e4-d0b2-4de9-b1bd-2d48f85c7859)

**Comment by def** [comment]
High `iowait` CPU usage occurs when the CPU is waiting for input/output (I/O) operations, such as reading or writing data to disk. Unfortunately, Coroot currently doesn't offer an easy way to display I/O usages for all volumes mounted on a specific node. However, you can manually check this using the `iostat` utility on the node.
