### ISSUE TITLE
Wrong link in coroot doc website

### ISSUE THREAD

**Issue by joeyleeeeeee97** [coroot/coroot#149]
in https://coroot.com/docs/coroot-community-edition/profiling/overview, the [Coroot-node-agent](https://github.com/coroot/coroot-cluster-agent) monitors running processes, gathers their profiles, and sends the profiles to the coroot-cluster-agent. is linking to cluster agent. 

I'd like a create a PR to fix this, but not found where coroot maintain the website

**Comment by apetruhin** [comment]
@joeyleeeeeee97, 
it's fixed, thank you.
