### ISSUE TITLE
The loop is unconditionally terminated

### ISSUE THREAD

**Issue by cristaloleg** [coroot/coroot#153]
Looks like these `break` should be there, isn't it?

https://github.com/coroot/coroot/blob/bd32d6f1ca3f8addd00ba097c96a79e10c684029/api/views/overview/health.go#L60
https://github.com/coroot/coroot/blob/bd32d6f1ca3f8addd00ba097c96a79e10c684029/api/views/overview/health.go#L72

Also, these 2 look suspicious to me

https://github.com/coroot/coroot/blob/bd32d6f1ca3f8addd00ba097c96a79e10c684029/watchers/deployments.go#L272
https://github.com/coroot/coroot/blob/bd32d6f1ca3f8addd00ba097c96a79e10c684029/watchers/deployments.go#L278

**Comment by apetruhin** [comment]
@cristaloleg,

The model allows having multiple SLIs of each kind, but in fact, Coroot supports only one for now. We are just checking if an SLI is defined.
