### ISSUE TITLE
Alerts on logging

### ISSUE THREAD

**Issue by BertoSwanepoel** [coroot/coroot#169]
Good day
We are using opentelemetry to collect logs and traces. I have setup alerting to our Teams channel. The notification is working as expected however the alerting on logs is not. Please see below picture. I have errors in my logs but the Erros: ok is green.

Please can you assist or advise.

Thank you
![image](https://github.com/coroot/coroot/assets/85493357/7a1c5b79-d418-4010-984e-acd67e7c4af0)

**Comment by BertoSwanepoel** [comment]
Hi,
Just to add some clarity on this matter.
I did more investigation and found that if the logs are coming from container logs then the alerting works as i can see the green light being amber. This is due to the coroot node agent getting those logs.
In my case I am sending the logs to opentelementry which is not monitored by the node agent, so no alerting can be done.

Hope this makes sense, and hope to hear from you soon.
thank you

**Comment by def** [comment]
Hi Berto,
This is a bug. Currently, Coroot calculates errors using log-based metrics. However, when logs are sent directly to otel-collector from the apps, the agent can't calculate metrics accurately.
To fix this, we can either compute the metrics on the otel-collector side or use raw logs for inspection.

**Comment by BertoSwanepoel** [comment]
Thank you,
Can you please elaborate on how I can achieve this. While we wait for a fix.
maybe an example of links.
Thank you

**Comment by def** [comment]
Unfortunately, I don't see any workarounds here. Both ways to fix this involve changes in Coroot's components
