### ISSUE TITLE
Ability to send alerts to webhook

### ISSUE THREAD

**Issue by ekersale** [coroot/coroot#17]
Hello Coroot Team! 

Really nice work on the tool. It would be awesome to develop webhook support for alert notification in order to support more external system .eg Microsoft Teams.

Thanks!

**Comment by johannmx** [comment]
Hi, in the meantime you can check this app for notifications [AppRise](https://github.com/caronc/apprise) it can be integrated with almost everything

**Comment by def** [comment]
We're working on this. 
It would be helpful to know what additional notification options Coroot users would like to use in addition to Slack and Microsoft Teams.

**Comment by apetruhin** [comment]
https://github.com/coroot/coroot/releases/tag/0.13.0
In addition to Slack, Coroot can now send notifications to Microsoft Teams, Pagerduty and Opsgenie.

**Comment by def** [comment]
We decided not to add support for custom web hooks so far. Instead, Coroot can be easily integrated with the following products:

| Integration           | [Alerts](https://coroot.com/docs/coroot-community-edition/alerting/overview) | [Deployment tracking](https://coroot.com/docs/coroot-community-edition/inspections/deployment-tracking) |
|-----------------------|----------|---------------------|
| Slack ([doc](https://coroot.com/docs/coroot-community-edition/alerting/slack))           | +        | +                   |
| Microsoft Teams ([doc](https://coroot.com/docs/coroot-community-edition/alerting/teams)) | +        | +                   |
| Pagerduty ([doc](https://coroot.com/docs/coroot-community-edition/alerting/pagerduty))       | +        | -                   |
| Opsgenie ([doc](https://coroot.com/docs/coroot-community-edition/alerting/opsgenie))        | +        | -                   |

Feel free to open another issue, if you need to add support for something else.

**Comment by aayushharwani-aidash** [comment]
Can we have a support for custom webhook, I am interested in working on it.

**Comment by Jipok** [comment]
https://github.com/coroot/coroot/pull/167
