### ISSUE TITLE
Application Discovery

### ISSUE THREAD

**Issue by ssnmworld** [coroot/coroot#19]
Hi, I installed coroot in our environment, and configured the prometheus url to discover the apps. in the logs, I see "0 nodes, 111 services, 211 applications' - But I do not see any application showing up in the UI.

Nodes - I understand the daemonset did not come up because of kernel version mismatch. 

Any clues ? 

Thanks

**Comment by apetruhin** [comment]
Hi, @ssnmworld
Coroot heavily relies on metrics produced by the coroot-node-agent (daemonset).
Please show us its logs.

**Comment by ssnmworld** [comment]
Hi Anton - Thanks for the quick reply.

In my environment, I could not bring up the node agent as our kernel version is 3.10 and the required version is 4.16. :-(

Thanks
