### ISSUE TITLE
 Issue with Enabling Profiling using Coroot's Official Helm Chart

### ISSUE THREAD

**Issue by YoranSys** [coroot/coroot#196]
I am encountering an issue while attempting to enable profiling with Coroot using the latest official Helm chart. Despite the agent seemingly collecting profiling information, the Coroot UI and logs indicate a problem.

Agent logs show that profiles are being collected and uploaded:
```
I0416 22:09:23.663882  337203 profiling.go:143] collected 27 profiles in 183ms
I0416 22:09:23.902719  337203 profiling.go:157] uploaded 27 profiles in 238ms
```

However, the `coroot-cluster-agent` log displays the following message every minute:
```
I0416 21:58:00.615599       1 profiles.go:159] scraped 0 targets in 0s
```

Additionally, the Coroot UI returns this error:
```
clickhouse error: code: 60, message: Table default.profiling_profiles doesn't exist
```

I am unable to locate the correct method to enable profiling. Any assistance would be greatly appreciated.

**Comment by apetruhin** [comment]
Hi @YoranSys,

At startup, Coroot is expected to create all the necessary tables. Please verify that you are using the most recent version - coroot:1.0.0-rc6 (included in the most recent Helm chart). Versions prior 1.0.0-rc3 have an issue where tables aren't created during initial setup if ClickHouse hasn't started yet.

**Comment by apetruhin** [comment]
You need to tell the node-agent what project's data it's gathering. 
The project ID is an 8-letter string that can be obtained from any project's URL.
<img src="https://github.com/coroot/coroot/assets/199054/42627396-90c9-448c-9194-0edd27a3ee73" width=50%>
To configure the node-agent with the project id, you should define the `--set node-agent.apiKey=PROJECT_ID_HERE` Helm variable.
It doesn't seem obvious at the moment, apologies for any confusion.
