### ISSUE TITLE
Support OTLP compression

### ISSUE THREAD

**Issue by oskoi** [coroot/coroot#201]
coroot doesn't support gzip OTLP compression and I am getting errors:
> E0422 08:50:52.858969       1 traces.go:44] proto: cannot parse invalid wire-format data

**Comment by oskoi** [comment]
And question. Will coroot allow to write traces/logs using otel collector directly to database (clickhouse) as before?
I'm using collector processors and don't know how to reuse them with new flow writing all telemetry to coroot api.

**Comment by def** [comment]
We decided to eliminate the otel collector to simplify integration, but you can use your own collector. Simply redirect logs/traces from the agents to your collector, and then send logs/traces to the Coroot instance over OTLP.

**Comment by apetruhin** [comment]
@oskoi,
I'm unable to reproduce the error. Could you please specify which OTLP proto version you are using?

**Comment by oskoi** [comment]
@def thanks! sounds like a good solution

@apetruhin you are right, the cause of the error is not in the OTLP version, but in the use of gzip compression. 
sorry for misleading...  I've updated issue

**Comment by apetruhin** [comment]
@oskoi, the latest Coroot version (1.0.2) now supports compressed OTLP data (gzip, zlib, zstd, snappy).
