### ISSUE TITLE
Support Search Trace

### ISSUE THREAD

**Issue by dtherhtun** [coroot/coroot#203]
Currently, we couldn't search traces by traceID.

**Comment by apetruhin** [comment]
Version [1.0.6](https://github.com/coroot/coroot/releases/tag/v1.0.6) introduces the ability to filter traces by `Root Service Name`, `Root Span Name`, and `Trace ID`.

<img width="908" alt="image" src="https://github.com/coroot/coroot/assets/199054/317010d4-3108-4788-b80d-22787dabe4d9">

**Comment by Runaho** [comment]
Hi @apetruhin and @def is there a way for searching traces by Attributes.
I saw Compare Attributes page, but it doesn't allow me to sort all traces by attribute; it only displays related single traces.

For instance, filters of this type would be ideal for my situation:
On the Application Traces page.

```
Attribute Query = custom_ip_attr is 192.0.0.1
Attribute Query = custom_attr has alue or bearer_token_attr is token
```

I suggest we begin by developing the equal filter first and subsequently implement the others one at a time.
If there is no existing way or development in progress for trace search by attribute queries and this feature is desired, I could attempt to implement it in my free time with some help i believe. Additionally, if development is already underway, I would love to review it.
