### ISSUE TITLE
Does coroot support clickhouse multi shards ?

### ISSUE THREAD

**Issue by YoranSys** [coroot/coroot#213]
Hello,
I tried to horizontally scale clickhouse to absorb more data but after scale to 3 shards it seem coroot display randomly one shard data only. 

Does coroot support clickhouse multi shards ?
Also how to configure retention  like max 7d of data ?

**Comment by apetruhin** [comment]
@YoranSys,
Currently, Coroot does not support sharded ClickHouse.

You can alter tables to change TTL. Here is the relevant discussion: https://github.com/orgs/coroot/discussions/50
