### ISSUE TITLE
k8s clusters with big amount of IPs per node emit too much metrics

### ISSUE THREAD

**Issue by rlex** [coroot/coroot#22]
Slack ref: https://coroot-community.slack.com/archives/C0443R3BW2G/p1677599077846269

Since IPVS is used, all k8s service IPs are getting attached to kube-ipvs0 interface on each kubernetes node.

As there is always some services running in host network (ssh, kubelet, haproxy, etc) it also generates metric per each IP attached to that network interface.

5000 services = 5000 metrics for each service, on each node.

On cluster with ~30 nodes, with 3.5k pods it amounts to around 1.5m TS in container_net_tcp_listen_info metric.

**Comment by rlex** [comment]
Probably related: https://github.com/kubernetes/kubernetes/issues/72236

**Comment by apetruhin** [comment]
@rlex, please update coroot-node-agent to version 1.6.6.

**Comment by rlex** [comment]
Yep, this solved this issue with IPVS IPs
