### ISSUE TITLE
Tracing Data Not Displaying

### ISSUE THREAD

**Issue by wang-qijia** [coroot/coroot#222]
The tracing data tracked via Java OpenTelemetry and exported to ClickHouse is not visible in the tracing menu. What could be the reason for this? 
The data exists in ClickHouse, but it is not visible in the tracing menu.

![image](https://github.com/coroot/coroot/assets/34878555/259e4dea-981e-4b51-836a-e460d3c9e5d2)

**Comment by furkandogmus** [comment]
I got same error on Golang...

**Comment by apetruhin** [comment]
Coroot was previously unable to function without metrics (Prometheus). This issue has been fixed in the latest version (1.0.6).

**Comment by wang-qijia** [comment]
> 之前，Coroot 在没有指标（Prometheus）的情况下无法运行。此问题已在最新版本（1.0.6）中修复。

My point is, the tracking data is already in ClickHouse, so why can't we see it on the page?
