### ISSUE TITLE
the image is not assembled

### ISSUE THREAD

**Issue by KKulishov** [coroot/coroot#225]
Downloaded ver [1.0.5](https://github.com/coroot/coroot/archive/refs/tags/v1.0.5.zip)

and 

`
docker build . -t coroot:test
`
gives this error
`
Step 9/16 : RUN go build -mod=readonly -ldflags "-X main.version=$VERSION" -o coroot .
 ---> Running in 5c260b9b7159
main.go:36:12: pattern static: no matching files found
The command '/bin/sh -c go build -mod=readonly -ldflags "-X main.version=$VERSION" -o coroot .' returned a non-zero code: 1
`
I made a clone of the project, but the error during assembly remained the same

Can you please tell me what could be the error?

**Comment by KKulishov** [comment]
I see /static/ is added to your exceptions in .gitignore

you can add a directory /static to complete the assembly

**Comment by eabykov** [comment]
I have the same problem

**Comment by KKulishov** [comment]
@apetruhin  can you help me

`
docker build . -t coroot:test
`
still doesn't work

gives this error
`
main.go:36:12: pattern static: no matching files found
`

**Comment by icylord** [comment]
run `mkdir static && touch static/file.txt && go vet ./...` before `docker build ***`

**Comment by icylord** [comment]
> @apetruhin can you help me
> 
> `docker build . -t coroot:test` still doesn't work
> 
> gives this error `main.go:36:12: pattern static: no matching files found`

run command `npm run build-prod` inside `front` folder to generate `static` folder

**Comment by KKulishov** [comment]
if need local build  docker [this](https://github.com/KKulishov/coroot/tree/main/.docker)
