### ISSUE TITLE
Missing .Net Metrics

### ISSUE THREAD

**Issue by johnrc90** [coroot/coroot#230]
Hey guys great project, being using for 2 months now in our production kubernetes cluster and its really helping us.

I was reading the docs and in the .Net Metrics section it said:

> The inspection is based on the [.NET runtime metrics](https://coroot.com/docs/metric-exporters/node-agent/metrics#dotnet) are automatically gathered by coroot-node-agent for every .NET runtime operating on the node. Therefore, there's no need for any manual configuration!

I have 2 ASP.NET webservers but the .Net metrics arent showing. We never used the diagnostic tool, and i was reading the microsoft [documentation](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/diagnostic-port) about it but i didnt find anything helpful. Theres a specific port or env variable we need to set so coroot can collect the metrics?

**Comment by def** [comment]
Could you please restart the node-agent on a node running a .NET application and share its log a few minutes after the restart?

**Comment by johnrc90** [comment]
Here:

[nodeagentlogs.txt](https://github.com/coroot/coroot/files/15403564/nodeagentlogs.txt)

**Comment by 64J0** [comment]
Related issue: https://github.com/coroot/coroot/issues/284
