### ISSUE TITLE
coroot could not complete the compilation

### ISSUE THREAD

**Issue by syzhang42** [coroot/coroot#231]
Is it convenient for you to provide your /static folder please?
I won't be able to compile without this folder.
![image](https://github.com/coroot/coroot/assets/155063522/4723c852-296a-471a-8520-5d3f50f8e5a4)

**Comment by apetruhin** [comment]
@syzhang42, use `npm` to build static:
```
cd front
npm ci
npm run build-prod
```

https://github.com/coroot/coroot/blob/main/CONTRIBUTING.md
