### ISSUE TITLE
Feature request: View profiling information per application instance

### ISSUE THREAD

**Issue by grzesuav** [coroot/coroot#248]
Slack discussion - [link](https://coroot-community.slack.com/archives/C0443R3BW2G/p1717168087903809?thread_ts=1717152097.955379&cid=C0443R3BW2G)

Currently node agent send profiling information per each instance of application, however when displaying in UI information is aggregated, which makes it difficult to navigate when particular instances have very different resource usage pattern.

I would like to see an option to select profile information from specific instance in the ui

**Comment by apetruhin** [comment]
[coroot-v1.6.4](https://github.com/coroot/coroot/releases/tag/v1.6.4)
