### ISSUE TITLE
Bug: UI sloppy with big service map

### ISSUE THREAD

**Issue by grzesuav** [coroot/coroot#249]
As on attached screenshot, when I select 3 days in time range there is a lot of pods connecting to the pod I am investigating. The service map graph makes UI very sloopy and till I navigate to the bottom (to the `cpu`/`instances` tabs) it take some time and struggle.

What I can think of is :
* making generation optional
* making it visible on its own tab
* something else ? Not sure

![image (5)](https://github.com/coroot/coroot/assets/9568421/52dc8d82-b566-470d-a8ae-d0b9dc2af189)

**Comment by grzesuav** [comment]
The pods on the left are I believe mostly periodic argo/spark/flink jobs. There are managed either directly by operator or via deployment in the middle, unsure right now, but they are cycling

**Comment by grzesuav** [comment]
second case is for kubelet - 
<img width="619" alt="image" src="https://github.com/coroot/coroot/assets/9568421/1af65adb-58c9-4a23-8c74-dd746b8c2195">

**Comment by def** [comment]
@grzesuav Coroot [v1.2.0](https://github.com/coroot/coroot/releases/tag/v1.2.0) includes several improvements related to this issue:

- Improved application grouping for Argo Workflows and Spark Applications
- Collapsible clients, dependencies, and instances lists on the map

Could you please update and validate it on your data?

**Comment by grzesuav** [comment]
hi @def !

Service map definetely look better now, however. in the `Net` panel I still have this issue, especially for our `prometheus` applications - see screenshot 

<img width="590" alt="image" src="https://github.com/user-attachments/assets/a186a8eb-fde0-47f8-b491-93011653da18">


I wanted to try out network bandwidth graph so I encounter this issue.


Second thing, would it be possible to distinguish `kubelet` connection (like for liveness and readiness probe) and be able to enable/disable them on view ? Not sure if this is valid ask though.
