### ISSUE TITLE
Coroot agent fails to detect and monitor KeyDB but detects Redis

### ISSUE THREAD

**Issue by YoranSys** [coroot/coroot#25]
I installed the coroot agent on my kubernetes cluster to monitor the performance of my KeyDB instance. However, I noticed that the agent is not able to detect and monitor KeyDB, whereas it is able to detect and monitor Redis on the same kubernetes cluster.

> KeyDB is a fork of redis the export is the same as Redis.

Steps to reproduce:

-     Install the coroot agent on the kubernetes cluster.
-     Install KeyDB and Redis on the same kubernetes cluster.
-     Check the coroot agent dashboard to see if both KeyDB and Redis are being monitored.

Expected behavior:
The coroot agent should be able to detect and monitor both KeyDB and Redis.

Actual behavior:
The coroot agent is only able to detect and monitor Redis. It is not able to detect and monitor KeyDB.

Additional information:

-     I am using the latest version of the coroot agent.
-     I have checked that KeyDB is running on the kubernetes cluster and is accessible.
-     I have checked the coroot agent logs and did not find any errors related to KeyDB.

Please let me know if there is anything else I can provide to help resolve this issue.

**Comment by apetruhin** [comment]
@YoranSys, please update to coroot:[0.14.3](https://github.com/coroot/coroot/releases/tag/0.14.3) and coroot-node-agent:[1.7.0](https://github.com/coroot/coroot-node-agent/releases/tag/v1.7.0)
