### ISSUE TITLE
Coroot does not support API key for Pyroscope API access

### ISSUE THREAD

**Issue by YoranSys** [coroot/coroot#26]
I am trying to use Coroot to access the Pyroscope API, but it seems that the Coroot does not support API key authentication for Pyroscope API access.

Expected behavior:
Coroot should be able to access the Pyroscope API using the provided API key.

Actual behavior:
Coroot is not able to access the Pyroscope API using the provided API key. The following error is displayed: "401 Unauthorized".

https://pyroscope.io/docs/server-api-reference/

**Comment by apetruhin** [comment]
@YoranSys, please update Coroot to version [0.14.3](https://github.com/coroot/coroot/releases/tag/0.14.3)

<img width="868" alt="image" src="https://user-images.githubusercontent.com/199054/223181021-4aa89000-8a65-4ef2-ad49-be8318d6ee68.png">
