### ISSUE TITLE
Support for HashiCorp Nomad

### ISSUE THREAD

**Issue by Shackelford-Arden** [coroot/coroot#269]
Hello there!

Wondering what it might look like to integrate w/ HashiCorp Nomad.

Fully aware that I'm in a minority, we do not use Kubernetes in our production environment.

I'm going to guess that this kind of integration would require some equivalent of [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) but for Nomad.

**Comment by def** [comment]
Coroot is compatible with HashiCorp Nomad. You can deploy Coroot outside your Nomad cluster using Docker Compose, and then install Coroot agents as Docker containers on each node within the cluster.

**Comment by def** [comment]
Coroot uses container metadata to group individual containers into applications:

- Here's how the agent composes container IDs for Nomad tasks: https://github.com/coroot/coroot-node-agent/blob/4787e1317b587695e942a311e894ed2ee488add3/containers/registry.go#L401
- Here's how Coroot groups Nomad applications: https://github.com/coroot/coroot/blob/main/constructor/containers.go#L44

**Comment by Shackelford-Arden** [comment]
Oh that's awesome, @def ! One of the few projects out there that already have Nomad in their sights, I love it!

I'll give this a whirl. 

Would there by any appetite to allowing that mapping for Nomad applications to be configurable? I'll try and sit down with the code and see if I can understand a bit more about how it works and whatnot too.

**Comment by Shackelford-Arden** [comment]
Since you do support Nomad, I'll go ahead and close this out for now though and open another issue if I feel there is a true need for further customization :)
