### ISSUE TITLE
MySQL Integration

### ISSUE THREAD

**Issue by KrisBuytaert** [coroot/coroot#283]
I`m trying to get the new MySQL functionality to work.

I've created users on the MySQL nodes, and configured coroot with the user/credentials for that user.
The coroot node can reach the mysql istances son 3306

After 10+ minutes I still don't see any data in the MySQL tab in coroot.

The only thing that resembles a database connection in the logs is the following error ..
Jul 05 15:57:35 coroot01 coroot[3027565]: E0705 15:57:35.119164 3027565 logs.go:193] handle packet: UNKNOWN (407): DB::Exception: Convert overflow: while executing 'FUNCTION toUnixTimestamp(Timestamp : 0) -> toUnixTimestamp(Timestamp) UInt32 : 7'

How do I debug this ?

**Comment by def** [comment]
This feature requires the installation of [coroot-cluster-agent](https://github.com/coroot/coroot-cluster-agent) (one instance per project). We have added this to the Helm chart, Docker Compose files and the systemd installation script.

**Comment by KrisBuytaert** [comment]
I totally missed the requirement of that agent ..  I have now  started that agent pointing it to my coroot instance and the api key for one project.. 

And that indeed gives more data ! thankx ! 

Is there any more documentation on this ?
