### ISSUE TITLE
Prometheus configuration add headers options

### ISSUE THREAD

**Issue by YoranSys** [coroot/coroot#30]
Hi,
When we use mimir we need to add some headers like `X-Scope-OrgID` to prometheus configuration? 

- https://grafana.com/docs/mimir/latest/operators-guide/secure/authentication-and-authorization/

Could you add this option ?

**Comment by apetruhin** [comment]
@YoranSys, this option was added in version 0.15.1

<img src="https://user-images.githubusercontent.com/199054/229772617-5ff167e4-bfa8-476b-9aef-50d4aa1c6300.png" alt="image" width="400">
