### ISSUE TITLE
Frequent Clickhouse errors DB::Exception: Convert overflow: while executing 'FUNCTION toUnixTimestamp(Timestamp : 0)  

### ISSUE THREAD

**Issue by KrisBuytaert** [coroot/coroot#304]
I`m bumping into frequent errors in the coroot log complaining about Clickhouse conversion errors.

Jul 31 12:31:58 coroot01.o11ylab.o11y.eu coroot[1140787]: E0731 12:31:58.458028 1140787 logs.go:193] handle packet: UNKNOWN (407): DB::Exception: Convert overflow: while executing 'FUNCTION toUnixTimestamp(Timestamp : 0) -> toUnixTimestamp(Timestamp) UInt32 : 7'
Jul 31 12:56:03 coroot01.o11ylab.o11y.eu coroot[1140787]: E0731 12:56:03.409933 1140787 logs.go:193] handle packet: UNKNOWN (407): DB::Exception: Convert overflow: while executing 'FUNCTION toUnixTimestamp(Timestamp : 0) -> toUnixTimestamp(Timestamp) UInt32 : 7'
Jul 31 13:23:58 coroot01.o11ylab.o11y.eu coroot[1140787]: E0731 13:23:58.451471 1140787 logs.go:193] handle packet: UNKNOWN (407): DB::Exception: Convert overflow: while executing 'FUNCTION toUnixTimestamp(Timestamp : 0) -> toUnixTimestamp(Timestamp) UInt32 : 7'
Jul 31 13:57:23 coroot01.o11ylab.o11y.eu coroot[1140787]: E0731 13:57:23.388024 1140787 logs.go:193] handle packet: UNKNOWN (407): DB::Exception: Convert overflow: while executing 'FUNCTION toUnixTimestamp(Timestamp : 0) -> toUnixTimestamp(Timestamp) UInt32 : 7'

The corresponding error in clickhouse looks like 

2024.07.31 13:57:23.335017 [ 6482 ] {7e3ee5ad-6b9d-4136-8fb7-b39c4d72c2df} <Error> TCPHandler: Code: 407. DB::Exception: Convert overflow: while executing 'FUNCTION toUnixTimestamp(Timestamp : 0) -> toUnixTimestamp(Timestamp) UInt32 : 7'. (DECIMAL_OVERFLOW), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c5c4fbb
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000077960ec
2. DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x00000000077a3e8b
3. bool DB::callOnIndexAndDataType<DB::DataTypeNumber<unsigned int>, DB::(anonymous namespace)::FunctionConvert<DB::DataTypeNumber<unsigned int>, DB::(anonymous namespace)::NameToUnixTimestamp, DB::(anonymous namespace)::ToNumberMonotonicity<unsigned int>>::executeInternal(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const::'lambda'(auto const&, DB::(anonymous namespace)::BehaviourOnErrorFromString)&, DB::(anonymous namespace)::BehaviourOnErrorFromString>(DB::TypeIndex, DB::(anonymous namespace)::FunctionConvert<DB::DataTypeNumber<unsigned int>, DB::(anonymous namespace)::NameToUnixTimestamp, DB::(anonymous namespace)::ToNumberMonotonicity<unsigned int>>::executeInternal(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const::'lambda'(auto const&, DB::(anonymous namespace)::BehaviourOnErrorFromString)&, DB::(anonymous namespace)::BehaviourOnErrorFromString&&) @ 0x000000000f47fc5e
4. DB::(anonymous namespace)::FunctionConvert<DB::DataTypeNumber<unsigned int>, DB::(anonymous namespace)::NameToUnixTimestamp, DB::(anonymous namespace)::ToNumberMonotonicity<unsigned int>>::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const (.bbec4b369713e2406103dfff8e75fc70) @ 0x000000000f47c7d3
5. DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x00000000080cbb6e
6. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f222750
7. DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f2232e1
8. DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000f224759
9. DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool, bool) const @ 0x000000001016d379
10. DB::ExpressionActions::execute(DB::Block&, bool, bool) const @ 0x000000001016e82e
11. DB::MergeTreeDataWriter::writeTempPartImpl(DB::BlockWithPartition&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::Context const>, long, bool) @ 0x0000000011b1498b
12. DB::MergeTreeSink::consume(DB::Chunk) @ 0x0000000011c711c4
13. DB::SinkToStorage::onConsume(DB::Chunk) @ 0x0000000012221982
14. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::ExceptionKeepingTransform::work()::$_1, void ()>>(std::__function::__policy_storage const*) @ 0x0000000012159f69
15. DB::runStep(std::function<void ()>, DB::ThreadStatus*, std::atomic<unsigned long>*) @ 0x0000000012159cf7
16. DB::ExceptionKeepingTransform::work() @ 0x00000000121593ea
17. DB::ExecutionThreadContext::executeTask() @ 0x0000000011f11d27
18. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000011f06610
19. DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x0000000011f06028
20. DB::TCPHandler::runImpl() @ 0x0000000011e86086
21. DB::TCPHandler::run() @ 0x0000000011e9c378
22. Poco::Net::TCPServerConnection::start() @ 0x0000000014768447
23. Poco::Net::TCPServerDispatcher::run() @ 0x00000000147688d9
24. Poco::PooledThread::run() @ 0x000000001485ed41
25. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001485d31d
26. start_thread @ 0x00000000000081ca
27. clone @ 0x0000000000039e73

**Comment by def** [comment]
This is fixed in v1.5

**Comment by KrisBuytaert** [comment]
Since I upgraded to v1.5  this error indeed has not occured again ..
