### ISSUE TITLE
OOM detection false positiv

### ISSUE THREAD

**Issue by tgruenert** [coroot/coroot#330]
OOM for rke2-agent is detected

![image](https://github.com/user-attachments/assets/c3a7a5cd-1c37-4e01-907a-ec53c41cfa81)

but not shown by `journalctl -k` 

OOM of a normal kubernetes deployment is shown like i expect it:

![image](https://github.com/user-attachments/assets/7ee105a2-daa3-4125-8d38-f1662d28cdcc)

according logline 
```
journalctl --since 2024-09-13 | grep "oom-killer"
Sep 13 13:13:42 n4.c1.*** kernel: mailpit invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=999
```

am I perhaps wrong? How can i verify coroot OOM signal in this case?

**Comment by def** [comment]
check the output of `dmesg` on the node

**Comment by tgruenert** [comment]
thank you @def. found it. `dmsg` was the tip.
