### ISSUE TITLE
update KSM version

### ISSUE THREAD

**Issue by soulwhisper** [coroot/coroot#367]
I am using kubernetes v1.31.1 with coroot.

coroot-kube-state-metrics report below logs

```shell
failed to list *v2beta2.HorizontalPodAutoscaler: the server could not find the requested resource
```

relates to [KSM-issue-1711](https://github.com/kubernetes/kube-state-metrics/issues/1711)

```shell
warning "autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler"
```

## suggest solution

update ksm app version to v2.7.0+, [ref](https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.7.0), [related-pr](https://github.com/kubernetes/kube-state-metrics/pull/1906)

**Comment by def** [comment]
@soulwhisper thanks for reporting this issue
