### ISSUE TITLE
COSTS tab can't parse json.

### ISSUE THREAD

**Issue by gkalwig** [coroot/coroot#37]
Hi,

We still have configuration I described in https://github.com/coroot/coroot/issues/20. 

I already reinstall our coroot and node-agents to see new feature and have error on COSTS tab. I looked in the documentation but couldn't find any information about it.

We have: 
![image](https://user-images.githubusercontent.com/87004230/231746333-685c6f58-a212-41c2-922e-a985acfc2887.png)
and in logs of container I only see:

```
W0413 11:17:52.309318       1 jvm.go:17] only one JVM per instance is supported so far, will keep only org.elasticsearch.launcher.CliToolLauncher
W0413 11:17:52.309403       1 jvm.go:17] only one JVM per instance is supported so far, will keep only org.elasticsearch.launcher.CliToolLauncher
W0413 11:17:52.309750       1 jvm.go:17] only one JVM per instance is supported so far, will keep only org.elasticsearch.launcher.CliToolLauncher
W0413 11:17:52.309774       1 jvm.go:17] only one JVM per instance is supported so far, will keep only org.elasticsearch.launcher.CliToolLauncher
I0413 11:17:52.322924       1 constructor.go:113] got 8 nodes, 159 services, 205 applications
I0413 11:17:52.322939       1 api.go:606] world loaded in 903.774258ms
E0413 11:17:52.504682       1 json.go:15] failed to encode: json: unsupported value: NaN

```

Can you help to resolve that issue? I miss something important?

UPDATE: we have karpenter, it spawns ondemands and spot nodes in that EKS cluster.

**Comment by apetruhin** [comment]
Hi @gkalwig, please update Coroot to version 0.16.1 and verify whether this issue has been resolved.

**Comment by gkalwig** [comment]
Hi @apetruhin, 

Thanks, it's showing up now. I'll keep an eye on the new features :)
