### ISSUE TITLE
Add dragonflydb support

### ISSUE THREAD

**Issue by maxpain** [coroot/coroot#374]
Hello. We use DragonflyDB instead of Redis, and it would be cool if Coroot would add support for this database.

**Comment by def** [comment]
The latest versions of Coroot and the agent support all Redis alternatives, including Redis, KeyDB, Valkey, and Dragonfly.
Coroot release: [v1.5.13](https://github.com/coroot/coroot/releases/tag/v1.5.13)
Coroot Node Agent release: [v1.22.1](https://github.com/coroot/coroot-node-agent/releases/tag/v1.22.1)
