### ISSUE TITLE
PostgreSQL traces are empty

### ISSUE THREAD

**Issue by deaDleSs-balLoon** [coroot/coroot#394]
I have a cloudnativepg postgres cluster. As it does not support sidecar containers for the moment, I deployed coroot-pg-agent as daemonset on each node, containing postgres instance. I also set the DSN for each agent to the IP address of the postgres instance on the same node. So now I have all metrics provided for postgres. It works ok.
I hoped that after configuring coroot-pg-agent I also will receive pg traces. But traces tab remains empty for the postgres cluster. At the same time I have traces for many other apps including coroot-pg-agent itself.

My environment:
* on-premise k8s-cluster  
*  coroot-node-agent installed as daemonset on each node
* coroot-pg-agent - as daemonset on each node with postgres
* coroot, victoriametrics and clickhouse installed on the separate host outside the cluster
* vm agent, kube-state-metrics in the cluster
* coroot-node-agent is configured to be scraped by vm agent (prometheus metrics) and to send profiles, traces and logs to coroot instance (`--logs-endpoint`, `--profiles-endpoint` and `--traces-endpoint` are configured)

So my questions are:
1) what conditions should be met for postgres traces to appear? 
2) should I install coroot-cluster-agent - it has no documentation at all - what it's used for?

**Comment by def** [comment]
PostgreSQL traces are gathered on the client side by `coroot-node-agent`. If you're referring to PostgreSQL-related metrics, you'll need to install `coroot-cluster-agent`. For more information about the cluster agent, check out the documentation here: https://coroot.com/docs/coroot/installation/architecture.

**Comment by def** [comment]
Which applications (programming languages) are accessing Postgres in your case? Is TLS being used?

**Comment by deaDleSs-balLoon** [comment]
Mostly Java. Sometimes PostgREST (Haskell?). TLS is enabled.

**Comment by def** [comment]
Unfortunately, java+TLS is not supported yet:(

**Comment by deaDleSs-balLoon** [comment]
So if I disable TLS, it will work? Thank you, will try!

**Comment by deaDleSs-balLoon** [comment]
Yes, with TLS off traces appeared. Thank you very much!
