### ISSUE TITLE
Add namespace filter for Overview application

### ISSUE THREAD

**Issue by cloud-66** [coroot/coroot#40]
For huge cluster with many namespacess it shows all application from whole cluster.
It would be great to see only application from one namespace

**Comment by creib** [comment]
Hi, 
you should be able to make use of the configuration/categories and define glob patterns in order to split by namespaces. This worked for me.

**Comment by apetruhin** [comment]
Coroot version [0.22.1](https://github.com/coroot/coroot/releases/tag/v0.22.1) introduces a namespace filter for the `Health`, `Service Map`, and `Deployments` views.
