### ISSUE TITLE
why can't get service map

### ISSUE THREAD

**Issue by tripitakav** [coroot/coroot#42]
![image](https://user-images.githubusercontent.com/73687556/236392801-726932a1-751f-42c4-9f6a-ca2838ad3b70.png)
![image](https://user-images.githubusercontent.com/73687556/236392844-42c2a1ce-99ff-4db1-a014-e4d41153d8b1.png)

**Comment by apetruhin** [comment]
@tripitakav 
* Which Coroot and coroot-node-agent versions are you using?
* Are there any errors in the logs?

**Comment by tripitakav** [comment]
> @tripitakav
> 
> * Which Coroot and coroot-node-agent versions are you using?
> * Are there any errors in the logs?

1. Coroot: v0.16.2 Node-agent:v1.7.6
2.
![image](https://user-images.githubusercontent.com/73687556/236417807-2878991d-195d-44ff-8d51-863b9d1547f2.png)
![image](https://user-images.githubusercontent.com/73687556/236418054-cfca9170-2ff8-4fb6-a548-c365dfd582e3.png)
There are no errors in the logs

**Comment by apetruhin** [comment]
Can you please share the output of the following Prometheus query?
```
node_info
```

**Comment by tripitakav** [comment]
> Can you please share the output of the following Prometheus query?
> 
> ```
> node_info
> ```

![image](https://user-images.githubusercontent.com/73687556/236512135-6edb8afc-3268-4e11-8817-825c105282ee.png)

**Comment by apetruhin** [comment]
We suspect that there are some issues with the way metrics are being relabeled, such as incorrect or missing labels.

Is this the right data source? The number of nodes doesn't match:

<img width="292" alt="image" src="https://user-images.githubusercontent.com/199054/236531907-7edc93ab-61a6-4c96-a7c7-c67c4997bd04.png">


versus

<img width="559" alt="image" src="https://user-images.githubusercontent.com/199054/236532164-e48325b1-6e97-4adf-b7bd-15c92cdde2b0.png">

**Comment by tripitakav** [comment]
I also think it should be due to incorrect or missing labels, because I deployed Coroot two months ago and everything was normal at that time. Then I deleted the namespace, and recently I had this issue when I was redeploying to demonstrate to the leader。

The data source is right,I'm just checking for node_info when selecting the metric, I chose staging-eks because the labels for both staging-eks and prod-hk metric are similar. Because I have deleted the prod-hk metric, only staging-eks have

**Comment by apetruhin** [comment]
@tripitakav
Let's check some other metric labels. One or two samples of each query will be enough:
1. `kube_node_info`
2. `kube_pod_info`
3. `container_info`

**Comment by apetruhin** [comment]
@tripitakav 
We guess that the metrics from `kube-state-metrics` (e.g., `kube_pod_info`, `kube_pod_labels`) no longer include the `uid` label after the relabeling process. Coroot needs this label load application instances.

**Comment by tripitakav** [comment]
> @tripitakav Let's check some other metric labels. One or two samples of each query will be enough:
> 
> 1. `kube_node_info`
> 2. `kube_pod_info`
> 3. `container_info`

1.
![image](https://github.com/coroot/coroot/assets/73687556/31eb5f49-7f7b-43aa-a391-e2b7ca0cdb0f)
2.
![image](https://github.com/coroot/coroot/assets/73687556/f88be878-30f4-4329-b4fc-3512226bfda4)
3.
![image](https://github.com/coroot/coroot/assets/73687556/63e2c9be-7562-449b-a9ec-c16cbe79ad17)

**Comment by tripitakav** [comment]
> @tripitakav We guess that the metrics from `kube-state-metrics` (e.g., `kube_pod_info`, `kube_pod_labels`) no longer include the `uid` label after the relabeling process. Coroot needs this label load application instances.

Yes,it don't has label include `uid`

**Comment by apetruhin** [comment]
Consider removing the rule that drops the `uid` label.
