### ISSUE TITLE
Is there any way to run coroot UI behind a proxy path `/coroot/`

### ISSUE THREAD

**Issue by rjshrjndrn** [coroot/coroot#44]
Hi,
First of all, thank you for this amazing project. 
Is there any way to run the UI behind a proxy path `/coroot`, like the nginx ingress controller, so that I can access it from anywhere(will be protected with oauth proxy)

**Comment by apetruhin** [comment]
@rjshrjndrn, thank you!

https://github.com/coroot/coroot/issues/13

**Comment by rjshrjndrn** [comment]
Thank you @apetruhin
