### ISSUE TITLE
Cant see the costs tab

### ISSUE THREAD

**Issue by onepabz** [coroot/coroot#46]
Hi there,

Thanks for the awesome work you guys are doing with coroot!

Im running the latest version of coroot (0.17.0) and the latest node-agent version (1.8.1).

I can see in prometheus that the metric `node_cloud_info` exists and is being exported properly by the node-adent.

But still I cant see the costs tab in the GUI:

![Screenshot 2023-05-18 at 12 10 08](https://github.com/coroot/coroot/assets/494757/b688e876-348b-42e1-8afd-c5d5500581b2)

Ive used the helm charts for installing it.
What am I doing wrong?

Thanks

**Comment by apetruhin** [comment]
@onepabz, could you please provide several samples of the `node_cloud_info` metric?

**Comment by onepabz** [comment]
node_cloud_info{account_id="redacted", availability_zone="us-east1-b", container="node-agent", endpoint="http", instance="10.5.100.171:80", instance_id="redacted", job="coroot/coroot-node-agent", machine_id="redacted", namespace="coroot", pod="coroot-node-agent-p2w7t", provider="GCP", region="us-east1"}
--

node_cloud_info{account_id="redacted", availability_zone="us-east1-c", container="node-agent", endpoint="http", instance="10.5.85.23:80", instance_id="redacted", job="coroot/coroot-node-agent", machine_id="redacted", namespace="coroot", pod="coroot-node-agent-4fthp", provider="GCP", region="us-east1"}


thanks @apetruhin

**Comment by def** [comment]
@onepabz, it appears that your cluster has metadata protection configured: https://cloud.google.com/kubernetes-engine/docs/how-to/protecting-cluster-metadata
The agent requires access to metadata in order to discover `instance_type` and `instance_lifecycle` (on-demand/preemptible)
