### ISSUE TITLE
kube-state-metrics not showing in project configuration

### ISSUE THREAD

**Issue by moophlo** [coroot/coroot#5]
I've configured coroot in a kubernetes cluster, but kube-state-metrics even if deployed is not showing in project configuration page

prometheus: ok
coroot-node-agent: 5 nodes found

```
NAME                 READY   UP-TO-DATE   AVAILABLE   AGE
kube-state-metrics   1/1     1            1           127m
```
I just followed this installation instructions:
https://coroot.com/docs/metric-exporters/kube-state-metrics/installation
Am I missing something?

**Comment by rlex** [comment]
I'm gonna assume kube-state-metrics should be scraped by prometheus specified in coroot, so KSM should either have servicemonitor or annotations, depending on your prometheus setup

**Comment by apetruhin** [comment]
@moophlo please check if there are any containers with id starting with `/k8s/` in your prometheus:
```
container_resources_cpu_usage_seconds_total{container_id=~"/k8s/.*"}
```

**Comment by drepig** [comment]
You can try another install way [.](https://github.com/devopscube/kube-state-metrics-configs).  And manually set the job in promethetus
```
kubectl edit configmap -n istio-system prometheus
```
And add job.
```
    - job_name: 'kube-state-metrics'
      static_configs:
        - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
 ```
You can find kube-state-metrics in your prometheus.
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/50312282/204803192-dc5c8e8a-7fad-4c97-a820-57e25a966090.png">

**Comment by drepig** [comment]
Add you can find your coroot is successfully deployed.

**Comment by def** [comment]
I don't see what else we can do here
