### ISSUE TITLE
[feature request] allow blacklisting of certain services

### ISSUE THREAD

**Issue by rlex** [coroot/coroot#6]
Hello! I'm not sure if this should be part of node-agent or UI, so putting it here.

I want to be able to blacklist certain services from UI. As an example, i have iscsid running on host nodes for longhorn (also used by openebs jiva, maybe something else too). It creates useless links on map (will be running on every node, connected to all instance managers with local replica, so there will be tons of them). Hardcoding them all to coroot code seems pointless, so maybe just add setting to hide those nodes from UI? 

On the other side, blacklisting them in agent (maybe with argument, like "--ignore-services=iscsid,haproxy"?) might reduce cardinality in prometheus, assuming those services will be dropped at probe time.

**Comment by apetruhin** [comment]
Hi @rlex! Thank you for feedback.
I'm pretty sure we'll make this feature.

**Comment by def** [comment]
You can use a custom app category to hide some applications on the overview 
https://github.com/coroot/coroot/releases/tag/0.6.0
