### ISSUE TITLE
Containerd memory usage in Cost tab

### ISSUE THREAD

**Issue by gkalwig** [coroot/coroot#60]
Hi,

In cost tab we can see high usage of memory by Containerd@<node-name> (or dockerd on previous K8s versions) but on my knowledge these memory is not used. It's only cached, so it shouldn't be visible on these usage bars. Information about we had 50-70% memory cached it's not give us anything usefull because it's standard behavior of linux system to use free memory as cache.

On example below we really have used less than 50% memory not ~80%, and containerd (magenta color) not use 38% memory.

![image](https://github.com/coroot/coroot/assets/87004230/3452a4e4-2694-47f9-af00-347ab4edd9c7)

![image](https://github.com/coroot/coroot/assets/87004230/b7064428-3c63-4ea3-a7a9-95ecc7723dc2)

![image](https://github.com/coroot/coroot/assets/87004230/6b7eb04b-64e3-4375-b676-3cc352ffaf3f)

**Comment by def** [comment]
I can't agree with you. 
For example, a Postgres server uses 32GB of page cache. While it is true that this memory can be reclaimed when needed, having such a cache is critical for database performance. Without it, query times would increase due to disk access. 
In this case, it is better to assume that this process is utilizing this amount of memory. Otherwise, if you don't take this into account when optimizing, it can negatively impact its performance.

**Comment by gkalwig** [comment]
Actually, from my perspective, you partly agreed with me, so I'll move on with my ideas to improve that page :)

I had another 2 point to support my point of view:

1. On this diagrams we correspond used vs requested. Where K8s don't care about how much memory is cached, OOM can occur only if all memory is used/container used more memory than limit. So how much memory is cached doesn't matter in the context of k8s behavior and distribution of the workload.
2. You give example of Postgresql, when i will deploy Postgresql on k8s. Still on that diagram i will have containerd memory use, not Postgresql container.

But if we still remain in the position that the display of the cached memory is correct, then I suggest:
- Let's not call it containerd / dockerd. Let's call it "cached" and give it some dark gray color or something like beige(#F5F5DC). On the other hand we can change "others" to dark gray, and give "cached" a light gray.

Best regards,

**Comment by def** [comment]
You've convinced me! :)

I really like your suggestion of having a separate element that reflects the size of page cache. This eliminates any potential misconception that this memory is "idle". 

We'll fix this soon.

Thank you!

**Comment by def** [comment]
This is fixed in Coroot v0.17.10
