### ISSUE TITLE
Mattermost as a notification channel

### ISSUE THREAD

**Issue by Split174** [coroot/coroot#61]
I'm following in the footsteps of [issue](https://github.com/coroot/coroot/issues/17) :smiley: . Are there plans to integrate with mattermost?

**Comment by sstolbov** [comment]
Best method of integration, i suppose, Web hook.
Web hook will satisfy everyone

**Comment by aayushharwani-aidash** [comment]
I am interested in working on it. Do we have any plans to integrate it ?

**Comment by kirillyu** [comment]
webhook also needed: telegram, rocketchat, grafana oncall are not covered for example

**Comment by Jipok** [comment]
webhook integration pr: https://github.com/coroot/coroot/pull/167

**Comment by KrisBuytaert** [comment]
I can actually confirm that WebHook integration works with Rocketchat, so I assume with Mattermost too , so I`m guessing this could be closed
