### ISSUE TITLE
pyroscope-ebpf-agent fail on openshift

### ISSUE THREAD

**Issue by tomer1983** [coroot/coroot#71]
after installing on prem i got the following error from pyroscope-ebpf-agent :
Error: unknown cri cri-o://1.23.5-7.rhaos4.10.git5cc2f1e.el8

I assume it failed because openshift used crio instead of docker
is there any fix/workaround  for that ?

**Comment by ajgillette** [comment]
Is there a work around for this or has it been addressed??

**Comment by def** [comment]
@tomer1983, @ajgillette, we are working on a solution to this problem. 
The issue is that Grafana Pyroscope deprecated `pyroscope-ebpf` in favor of `grafana-agent`. We plan to integrate `pyroscope-ebpf` into `coroot-node-agent` to support all container types and runtimes

**Comment by apetruhin** [comment]
We integrated eBPF CPU profiler into `coroot-node-agent`. Please upgrade/install Coroot using the latest helm chart.

https://github.com/coroot/coroot/releases/tag/v0.23.0
https://github.com/coroot/coroot-node-agent/releases/tag/v1.15.0
