### ISSUE TITLE
[feature request] allow customization of monitoring-related namespaces

### ISSUE THREAD

**Issue by rlex** [coroot/coroot#8]
Hello, it seems that namespaces related to monitoring are hardcoded:
https://github.com/coroot/coroot/blob/5e461f4dafe3935e9d610825282f1bed227c55f5/model/application.go#L119
It will be nice if they can be customized, for example i have parca in ns parca which is also related to monitoring, and i bet other people have different software in different namespaces too.

**Comment by rlex** [comment]
guess 0.6.0 fixes that?

**Comment by def** [comment]
yeah, and #6 as well (you can use some category, e.g. "hidden", to hide some applications on the overview)
