### ISSUE TITLE
 Table default.otel_traces does not exist

### ISSUE THREAD

**Issue by JellyZero** [coroot/coroot#81]
![image](https://github.com/coroot/coroot/assets/109566229/2d047830-2255-41f6-96b4-7bf18daa58d2)

**Comment by def** [comment]
Coroot's Helm chart installs the OpenTelemetry Collector, which creates all the required tables in ClickHouse and exports traces to it.

**Comment by JellyZero** [comment]
Can you provide an example of Docker installation？

**Comment by aarvee11** [comment]
![image](https://github.com/coroot/coroot/assets/15531173/8a3c04af-53ec-4326-91f9-896596714e2a)
did not create in our case and we are also facing the same issue.

**Comment by def** [comment]
Now, Coroot manages tables in ClickHouse directly and no longer relies on the otel-collector
