### ISSUE TITLE
Is there a plan to support the collection of Trace and Log ？

### ISSUE THREAD

**Issue by tripitakav** [coroot/coroot#96]
Is there a plan to support the collection of Trace and Log, similar to Signoz, to become an all in one observable platform

**Comment by def** [comment]
@tripitakav Coroot already has the [Distributed Tracing](https://coroot.com/docs/coroot-community-edition/tracing/overview) capability, and full-featured log monitoring is on the way.

**Comment by tripitakav** [comment]
@def Thanks! Really looking forward to the log monitoring.

**Comment by def** [comment]
@tripitakav we've released log monitoring recently: https://github.com/coroot/coroot/releases/tag/v0.20.0
